name: AeterumItemsAndTools
version: '${project.version}'
main: me.figgnus.aeterumitemsandtools.AeterumItemsAndTools
api-version: '1.20'
commands:
  randomizer:
    description: "Gives player randomizer tool"
    usage: /<command>
